BEGIN TRAN
GO
ALTER TABLE dbo.OrderHeader
 ADD CreateDate DATETIME NULL CONSTRAINT dfCreateDate DEFAULT GETDATE(),
     ModifiedDate DATETIME NULL CONSTRAINT dfModifiedDate DEFAULT GETDATE()
GO
IF @@ERROR = 0
	COMMIT
ELSE 
	ROLLBACK
GO
